name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: System info
        run: |
          echo $USER
          df -h
          free -m
          lscpu

      - name: Install
        run: |
          sudo apt update
          sudo apt install gdal-bin parallel optipng jq

      - name: Create data directory and set ownership
        run: |
          sudo mkdir /mnt/data
          sudo chown $USER:$USER /mnt/data

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Download data
        run: scripts/download.sh

      - name: Convert DEM to hillshade
        run: scripts/dem2hillshade.sh
